/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as TagihanRouteImport } from './routes/tagihan'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LimitRouteImport } from './routes/limit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const TagihanRoute = TagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitRoute = LimitRouteImport.update({
  id: '/limit',
  path: '/limit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/limit': typeof LimitRoute
  '/profil': typeof ProfilRoute
  '/tagihan': typeof TagihanRoute
  '/topup': typeof TopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/limit': typeof LimitRoute
  '/profil': typeof ProfilRoute
  '/tagihan': typeof TagihanRoute
  '/topup': typeof TopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/limit': typeof LimitRoute
  '/profil': typeof ProfilRoute
  '/tagihan': typeof TagihanRoute
  '/topup': typeof TopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/limit' | '/profil' | '/tagihan' | '/topup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/limit' | '/profil' | '/tagihan' | '/topup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/limit'
    | '/profil'
    | '/tagihan'
    | '/topup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LimitRoute: typeof LimitRoute
  ProfilRoute: typeof ProfilRoute
  TagihanRoute: typeof TagihanRoute
  TopupRoute: typeof TopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagihan': {
      id: '/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof TagihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limit': {
      id: '/limit'
      path: '/limit'
      fullPath: '/limit'
      preLoaderRoute: typeof LimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LimitRoute: LimitRoute,
  ProfilRoute: ProfilRoute,
  TagihanRoute: TagihanRoute,
  TopupRoute: TopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
